apiVersion: v1
kind: Pod
metadata: { name: compliant, namespace: pe-security }
spec:
  automountServiceAccountToken: false
  securityContext: { runAsNonRoot: true, seccompProfile: { type: RuntimeDefault } }
  containers:
    - name: app
      image: busybox:1.37.0
      command: ["sleep", "3600"]
      securityContext:
        allowPrivilegeEscalation: false
        capabilities: { drop: ["ALL"] }
        runAsUser: 65534
